# Generated by Django 5.1.7 on 2025-03-25 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kitob haqida')),
                ('weight', models.IntegerField(verbose_name="Og'irligi")),
                ('internal_number', models.IntegerField(unique=True, verbose_name='Ichki raqam')),
                ('book_language', models.CharField(max_length=255, verbose_name='Kitob tili')),
                ('written_language', models.CharField(max_length=255, verbose_name='Yozilgan tili')),
                ('translator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kim tarjima qigani')),
                ('book_pages', models.IntegerField(verbose_name='Sahifalar soni')),
                ('book_cover', models.CharField(max_length=255, verbose_name='Kitob muqovasi')),
                ('book_type', models.CharField(choices=[('elektron', 'Elektron'), ('bosma', 'Bosma')], default='bosma', max_length=10, verbose_name='Kitob turi')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Kitob fayli')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ombordagi soni')),
                ('year_publication', models.IntegerField(verbose_name='Nashr yili')),
                ('country_origin', models.CharField(max_length=255, verbose_name='Nashr Mamlakati')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('discount_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Chegirma narxi')),
                ('is_discount', models.BooleanField(default=False, verbose_name="Chegirma bor yoki yo'q")),
                ('is_free', models.BooleanField(default=False, verbose_name="Bepulmi yoki yo'q")),
                ('is_published', models.BooleanField(default=False, verbose_name="Nashr qilinganmi yoki yo'q")),
                ('is_featured', models.BooleanField(default=False, verbose_name="Taniqli kitobmi yoki yo'q")),
                ('is_bestseller', models.BooleanField(default=False, verbose_name="Eng ko'p sotilgan kitobmi yoki yo'q")),
                ('is_new', models.BooleanField(default=False, verbose_name="Yangimi yoki yo'q")),
                ('is_popular', models.BooleanField(default=False, verbose_name="Ommabopmi yoki yo'q")),
                ('is_top_rated', models.BooleanField(default=False, verbose_name="Eng yaxshi reytingga ega kitobmi yoki yo'q")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='books/images/')),
                ('is_main', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.category'),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
