# Generated by Django 5.1.7 on 2025-03-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimage',
            name='book',
        ),
        migrations.AddField(
            model_name='bookimage',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book'),
            preserve_default=False,
        ),
    ]
