# Generated by Django 5.1.7 on 2025-03-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_top_rated',
            field=models.BooleanField(default=False, verbose_name="Eng yaxshi reytingga ega kitobmi yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name="Eng ko'p sotilgan kitobmi yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name="Chegirma bor yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name="Taniqli kitobmi yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name="Bepulmi yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name="Yangimi yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name="Ommabopmi yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name="Nashr qilinganmi yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(verbose_name='Nashr sanasi'),
        ),
    ]
