# Generated by Django 5.1.7 on 2025-03-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_is_top_rated_alter_book_is_bestseller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ombordagi soni'),
        ),
    ]
