# Generated by Django 5.1.7 on 2025-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Chegirma narxi'),
        ),
    ]
